### PR TITLE
Use 5a1t version

### PR DESCRIPTION
**Pull request by raimondious**
This version makes Robin a lot nicer with multiple channels.  I thought it would be nice for everyone to get on the same version.  For reasons I can't grasp, @dashed didn't want to make a PR, so I'm making one for them.

@vartan Would you consider adding the contributors on 5a1t/robin-grow to your repo? Then we don't have this fragmentation.

### CODE REVIEW

**Comment by vartan** [comment]
Wow this is awesome. I will definitely add as contributors

**Comment by vartan** [comment]
I noticed that the link to the github is wrong in the versioning on the sidebar, and that the sidebar scrolls up automatically occasionally. Any idea?

**Comment by vartan** [comment]
Added a couple of people. You guys can fix this up and merge it in :)

**Comment by vartan** [comment]
I would bump this up to 1.0 also when you're done merging :)

**Comment by Bottswana** [comment]
Referencing this issue: https://github.com/vartan/robin-grow/issues/111

**Comment by dashed** [comment]
To be clear: I'm not doing the rebasing work on this PR.

**Comment by Bottswana** [comment]
May I suggest given how big this is, we branch off and merge after testing?

**Comment by vartan** [comment]
I'm gonna close this until we get a good merge ready

**Pull request closed without merging**
