### PR TITLE
Adds ping noise for username mentions in chat.

### PR DESCRIPTION
**Pull request by wwwroth**
Unfortunately this is not complete and I have to leave my desk but the foundation is laid. Just need to add global variables to all username mentions and you should be good. Cheers.

### CODE REVIEW

**Comment by dashed** [comment]
@wwwroth woah awesome :+1:

**Comment by vartan** [comment]
rebase please?

**Comment by tetra-fox** [comment]
added in f824a93

**Comment by wwwroth** [comment]
@wc1202 DOMNodeInserted -- excellent. This gets around counting all of the mentions and not having to store it in memory.

**Pull request closed without merging**
