### PR TITLE
Attempt to save a dead channel (Implements #71)

### PR DESCRIPTION
**Pull request by Phoenix616**
This PR adds an option in the settings menu that will try to save a channel that is dead (less then half of the people voted for **grow**) by switching to **stay** in the last two minutes.

### CODE REVIEW

**Comment by dkisselev** [comment]
But if the majority is abandon/no vote, even if all the grow people move to stay, the channel wouldn't have stay majority to get through it.  I guess you would gain a few hundred because of the people that always live in stay, but I don't think it will be enough in most cases.

**Comment by Phoenix616** [comment]
Well my attempt will only work in the case that grow and stay are fighting each other and not if the room has already been taken over by no-voters. Not sure how one would detect that before it happens. 

Maybe something like if a third of the people don't vote expect that the room would be dead the next merge? Or try to calculate in the people that are already afk? Not sure how exact that would be in the end or if you can even get the afk count.

One could also add a message to notify others without the script that the room is dead but that's too spammy imo.

**Comment by vartan** [comment]
rebase please?

**Comment by Phoenix616** [comment]
My current implementation doesn't really help much. Would be better to check for the "no compatible room found" message or something that indicates that no new merges will happen in the near future.

I'm closing this pr as it uses a complete other, broken implementation as indicated by @dkisselev.

**Pull request closed without merging**
