### PR TITLE
Channel filter

### LINKED ISSUE #49: Whitelist partial messages
Whitelist messages with a custom prefix e.g. '`PCFLMSG:`'  to filter out spam in larger rooms.

### PR DESCRIPTION
**Pull request by dashed**
Closes #49

### CODE REVIEW

**Comment by dashed** [comment]
Example:

screen shot 2016-04-02 at 10 49 28 am

**Comment by vartan** [comment]
This has been widely regarded as the greatest feature of all time. Thanks!!

**Comment by dashed** [comment]
@vartan No problem :+1:

**Comment by dashed** [comment]
@vartan I reached T16, and chat would've been impossible without the filters. :smile:

**Pull request merged**
