### PR TITLE
Make slash commands work in chat again (minor annoyance).

### PR DESCRIPTION
**Pull request by mootinator**
Solves the issue where if you type a slash while in a channel, it gets sent to chat. Deletes the channel text when you lead off with a slash.

### CODE REVIEW

**Comment by vartan** [comment]
Can anyone verify this works

**Comment by Bottswana** [comment]
This was fixed with this PR anyway: https://github.com/vartan/robin-grow/pull/130
It refactored command processing which indirectly fixed /commands.

**Comment by mootinator** [comment]
This is a little more usable, yet, but feel free to close it.

**Comment by vartan** [comment]
I think i fixed this in the main branch

**Comment by vartan** [comment]
Let me know if not

**Pull request closed without merging**
