### PR TITLE
Full-screen-height chat area

### PR DESCRIPTION
**Pull request by voltaek**
For desktop resolutions, expands the chat area to use the full browser window height. Also hides the footers to get more vertical space without showing a scrollbar.

### CODE REVIEW

**Comment by devoidfury** [comment]
We probably shouldn't remove reddit's legal policy links in the bottom.

**Comment by voltaek** [comment]
Updated as you requested @devoidfury

**Comment by vartan** [comment]
Can you rebase it so it can be quickly merged?

**Comment by voltaek** [comment]
Ok, @vartan and @devoidfury, should be good to go

**Pull request merged**
