### PR TITLE
Give user the choice what to do

### PR DESCRIPTION
**Pull request by PeachIceTea**
Fixes issue #46 and fulfills request #54

### CODE REVIEW

**Comment by curioussavage** [comment]
:+1:

**Comment by dkisselev** [comment]
I don't think you mean to roll the version # back..

**Comment by dashed** [comment]
@dkisselev bad merge on his part :P just need a rebase

**Comment by PeachIceTea** [comment]
Thanks for catching that.

**Comment by dashed** [comment]
@PeachIceTea do you want to start a fork of this project to get all this and all other PRs to be merged?

**Comment by PeachIceTea** [comment]
@dashed nah I am sure he will come back. Splitting up is almost always bad.

**Comment by dashed** [comment]
I'm going to maintain a personal fork here: https://github.com/dashed/robin-grow

**Comment by vartan** [comment]
Sorry I was gone. I'll add this.

**Comment by vartan** [comment]
Any way you can rebase this?

**Comment by PeachIceTea** [comment]
Don't worry everybody has a real life. Sure will do.

**Pull request merged**
