### PR TITLE
Auto spam protection

### PR DESCRIPTION
**Pull request by codyrobert**
The gist is, if the same username is posting the same message 3 or more times, it's probably spam and should be hidden. Thoughts?

### CODE REVIEW

**Comment by vartan** [comment]
I am not yet sure if im comfortable banning users from talking, for now I am filtering out messages starting with "[".

**Comment by codyrobert** [comment]
Totally agree with that concern - I'll clarify.

The intent is not to ban users, but if a single user posts the same message 3 or more times, that specific message from that specific user is hidden.

But any other message they post is untouched.

**Comment by vartan** [comment]
Oh okay that is cool, although it will miss a lot of spam that is mostly the same (stats-bots). Maybe we should provide an interface for spam strings, and let it filter out spam strings.

**Comment by codyrobert** [comment]
I think the mix of both of these methods is probably good and provides adequate coverage. An interface would be cool, but time-intensive (at least as far as what time I have available right now).

**Comment by codyrobert** [comment]
If you do want to merge this pr, I can update it so it doesn't conflict with the current on master?

**Comment by vartan** [comment]
That sounds good

**Comment by vartan** [comment]
We might want to consider limiting (pruning) the size of the chat if we're gonna be looping through the messages, or at least providing an option for the user to do that.

**Pull request merged**
