### PR TITLE
Use MutationObserver for more efficient and instant botspam removal

### PR DESCRIPTION
**Pull request by Shou**
Can probably be applied to the hash/duplicate removal functionality too.

### CODE REVIEW

**Comment by vartan** [comment]
Check out the changes I just made in the newest push

**Comment by Shou** [comment]
That works, but it's not as efficient as MO because it observes the entire document for changes instead of just the chat messages, and it doesn't give you the specific updated posts like MO so you don't have to loop through the list of messages on every spam removal.

**Comment by Shou** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

It was basically deprecated in favor of MutationObserver.

**Comment by vartan** [comment]
That's true, if you want to convert it all over please update your merge request.

**Comment by vartan** [comment]
We should also update findAndHideSpam so that it will work incrementally so it doesn't have to go through the entire list every time as we do this

**Comment by codyrobert** [comment]
I was getting started on the incremental filtering but stopped after your recent updates @vartan. Are you going to continue with this one @Shou? Figure I ask rather than duplicate efforts.

**Comment by Shou** [comment]
@codyrobert Yeah I'm on it

**Comment by dashed** [comment]
Removal of any and all `setInterval` is :+1:

**Comment by Shou** [comment]
This should be safe to merge now.

**Pull request merged**
