### PR TITLE
Standings Viewer

### PR DESCRIPTION
**Pull request by mootinator**
Added a Standings viewer that auto-highlights the current room if it is in the list, sourced from the "official" Reddit thread. (This version doesn't break the page on close.)

### CODE REVIEW

**Comment by vartan** [comment]
I'm not super comfortable opening up more outgoing connections. I'm gonna wait on this to see what people think about this before committing to it

**Comment by devoidfury** [comment]
I'm with vartan, not sure we want more connections on this

**Comment by dashed** [comment]
:-1: agree. Don't do this.

**Comment by mootinator** [comment]
Not that it matters all that much, but it is implemented as "Doesn't do anything unless you interact with it," The biggest problem is likely the potential for the post to change format, as opposed to anything performance related.

**Comment by vartan** [comment]
If you add this behind a button and source the information from a reddit thread, then I might consider it. 

If it already meets these requirements let me know

**Comment by mootinator** [comment]
It is behind a button and sources from a Reddit thread, yes. 

image

It's clearer to me now that I shouldn't have pruned the "Est. Tier" column.

**Comment by vartan** [comment]
Oh awesome. Yeah tier would be cool too

**Comment by vartan** [comment]
if you rebase to current version i'll patch it in

**Comment by mootinator** [comment]
There's the inherent risk of the post being screwy showing itself. 
image

Okay, I'll try to rebase.

**Comment by mootinator** [comment]
I'll re-open this request on the new branch.

**Pull request closed without merging**
