### PR TITLE
semicolons

### PR DESCRIPTION
**Pull request by tetra-fox**

### CODE REVIEW

**Comment by devoidfury** [comment]
Semicolons are mostly optional, will leave this up to vartan

**Comment by tetra-fox** [comment]
okay

**Comment by vartan** [comment]
I like semicolons, :P

**Comment by tetra-fox** [comment]
@vartan i'm adding another feature, i'll add them with the new feature

(its storing the muted users in a cookie)

**Comment by vartan** [comment]
Use the settings variable?

**Comment by tetra-fox** [comment]
ugh it keeps throwing errors no matter what i do

**Comment by wc1202** [comment]
okay just got it working, now i need to make them show in the muted list on load

**Pull request closed without merging**
