### PR TITLE
Linkify URLs posted in chat

### PR DESCRIPTION
**Pull request by xBytez**
Confirmed working.
~~Does NOT work with own chat messages.~~

Can (read: should) be cleaned up but basic functionality works.

### CODE REVIEW

**Comment by vartan** [comment]
I was just about to request someone make this. Thanks

**Comment by vartan** [comment]
~~I saw someone post a link http://test.com , didn't linkify?~~

Nevermind it works

**Comment by xBytez** [comment]
You're welcome! Should open links in new tabs. I do hope someone wants to clean it up because it's not the cleanest of code. I've only tested this on Chrome 51 (canary)

looks like this:

**Comment by xBytez** [comment]
I lied, does work with own chat messages.

**Comment by KronK0321** [comment]
Does this work with http:// links? In testing, I found https:// worked but http:// did not.

#132

**Pull request merged**
