### PR TITLE
only run findSpam/prune when a message passes

### PR DESCRIPTION
**Pull request by devoidfury**

### CODE REVIEW

**Comment by vartan** [comment]
Did I just do the same thing? Also are we accidentally filtering out system messages?

**Comment by devoidfury** [comment]
Heh, you might have. The pruner might pull out system messages when the number gets too high, yeah

**Comment by vartan** [comment]
Not the pruner, but the channel filter.

**Comment by devoidfury** [comment]
Ah, the channel filter might filter system messages, yeah

**Pull request merged**
